name: Deploy Prefect flow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Debug working directory
          run: |
            echo "Workspace: ${{ github.workspace }}"
            ls -la ${{ github.workspace }}
          
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Authenticate with Prefect Cloud
          run: |
            echo ${{ secrets.PREFECT_API_KEY }}
            prefect cloud login --key ${{ secrets.PREFECT_API_KEY }}  --workspace "chinmaya-balaji/default"

        - name: Deploy Prefect Flow
          run: |
            prefect deployment apply prefect.yaml
          working-directory: ${{ github.workspace }}

